version: '3.4'

services:
  dealersanddistributorsclient:
    image: dealersanddistributorsclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5004:5004
